<?php
// $Id;

/**
 * @file
 *   IDS View Plugin default parameters.
 *
 */

if (!defined('IDS_API_LIBRARY_PATH')) define('IDS_API_LIBRARY_PATH', 'idsapi/');
if (!defined('IDS_API_ENVIRONMENT')) define('IDS_API_ENVIRONMENT', 'wordpress');

define('IDS_VIEW_MENU_TITLE', 'IDS View');

define('IDS_VIEW_DEFAULT_LANGUAGE', 'en');
define('IDS_VIEW_DISPLAY_ERRORS', TRUE);

/* Widget's default parameters */

define('IDS_VIEW_WIDGET_ASSETS_TYPE', 'documents');
define('IDS_VIEW_WIDGET_TITLE', 'IDS Updates');
define('IDS_VIEW_WIDGET_NUM_ITEMS', 10);



